[package]
name = "fedimint-sled"
description = "fedimint-sled provides a sled-backed database implementation for Fedimint."
version.workspace = true
authors.workspace = true
edition.workspace = true 
documentation.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true 

[lib]
name = "fedimint_sled"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
fedimint-api = { path = "../fedimint-api" }
sled = "0.34"
tracing = "0.1.37"

[dev-dependencies]
tempfile = "3.3.0"
test-log = { version = "0.2", features = [ "trace" ], default-features = false }
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
