[package]
name = "rest-client-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clientd = { path = "../clientd" }
mint-client = { path = "../client-lib" }
minimint-api = { path = "../../minimint-api" }
minimint-core = { path = "../../minimint-core" }
anyhow = "1.0.58"
base64 = "0.13.0"
bitcoin = "0.27.0"
clap = { version = "3.1.18", features = ["derive"] }
reqwest = { version = "0.11.0", features = [ "json" ] }
tokio = { version = "1.0.1", features = ["full"] }
lightning-invoice = "0.14.0"
serde = { version = "1.0.118", features = [ "derive" ] }
serde_json = { version = "1"}