[package]
name = "fedimint-mint-server"
description = "fedimint-mint is a chaumian ecash mint module."
version.workspace = true
authors.workspace = true
edition.workspace = true 
documentation.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fedimint_mint_server"
path = "src/lib.rs"

[dependencies]
async-trait = "*"
fedimint-api = { path = "../../fedimint-api" }
fedimint-mint-common = { path = "../mint-common/" }
tracing ="0.1.37"
