[package]
name = "fedimint-bitcoind"
description = "Bitcoin Core connectivity used by Fedimint"
version.workspace = true
authors.workspace = true
edition.workspace = true 
documentation.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fedimint_bitcoind"
path = "src/lib.rs"

[features]
bitcoincore-rpc = [ "dep:bitcoincore-rpc" ]
default = []

[dependencies]
anyhow = "1.0.66"
bitcoin = "0.29.2"
bitcoincore-rpc = {version = "0.16.0" , optional = true }
async-trait = "*"
fedimint-api  = { path = "../fedimint-api" }
rand = "0.8"
serde = { version = "1.0.145", features = [ "derive" ] }
tracing = "0.1.37"
thiserror = "1.0.37"
                   
