[package]
name = "fedimint-mint-client"
description = "fedimint-mint is a chaumian ecash mint module."
version.workspace = true
authors.workspace = true
edition.workspace = true 
documentation.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true 

[lib]
name = "fedimint_mint_client"
path = "src/lib.rs"

[dependencies]
fedimint-api = { path = "../../fedimint-api" }
fedimint-mint-common = { path = "../mint-common/" }
tracing ="0.1.37"
