[package]
name = "fedimint-client"
description = "mint-client provides a library for sending transactions to the federation."
version.workspace = true
authors.workspace = true
edition.workspace = true 
documentation.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fedimint_client"
path = "src/lib.rs"


[dependencies]
bitcoin = "0.29.2"
fedimint-api  = { path = "../fedimint-api/" }
thiserror = "1.0.30"

[dev-dependencies]
fedimint-mint-client = { path = "../modules/mint-client" }
fedimint-api = { path = "../fedimint-api/" }
