[package]
name = "fedimint-derive"
description = "fedimint-derive provides helper macros for serialization."
version.workspace = true
authors.workspace = true
edition.workspace = true 
documentation.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true 

[lib]
proc-macro = true
name = "fedimint_derive"
path = "src/lib.rs"

[features]
diagnostics = []

[dependencies]
heck = "0.4"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
