[package]
name = "tbs"
description = "tbs is a helper cryptography library for threshold blind signatures"
version.workspace = true
authors.workspace = true
edition.workspace = true 
documentation.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
unstable = []

[lib]
name = "tbs"
path = "src/lib.rs"

[dependencies]
bls12_381 = { version = "0.7.0", features = [ "zeroize", "groups" ] }
ff = "0.12.1"
group = "0.12.1"
hex = "0.4.2"
rand = "0.8"
rand_chacha = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
sha3 = "0.10.5"

[dev-dependencies]
bincode = "1.3.1"
clap = { version = "4.0.22", features = ["derive"] }
