[package]
name = "hkdf"
description = "RFC5869 HKDF implementation on top of bitcoin_hashes"
version.workspace = true
authors.workspace = true
edition.workspace = true 
documentation.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "hkdf"
path = "src/lib.rs"

[dependencies]
bitcoin_hashes = "0.11.0"
