# This is a basic workflow to help you get started with Actions

name: "CI (nix)"

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Code Coverage will build using a completely different profile (neither debug/release)
  # Which means we can not reuse much from `build` job. Might as well run it as another
  # build in parallel
  ccov:
    name: "Code coverage"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: cachix/cachix-action@v10
        with:
          name: fedimint
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build and run tests with Code Coverage
        run: nix build -L --extra-experimental-features nix-command --extra-experimental-features flakes .#workspaceCov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: result/lcov.info
          fail_ci_if_error: true
