on: [push, pull_request]

name: CI

jobs:
  build_and_unit_test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: clippy, rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: version
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace
      - uses: actions-rs/cargo@v1
        with:
          command: doc
      - name: Doc warnings
        run: "[ $(cargo doc 2>&1 | grep -v 'output filename collision' | grep warning | wc -l) == 0 ]"
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  build_and_integration_test:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - run: scripts/integrationtest.sh