[package]
name = "fedimint-build"
description = "fedimint is the main consensus code for processing transactions and REST API"
version.workspace = true
authors.workspace = true
edition.workspace = true 
documentation.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true 

[features]

[lib]
name = "fedimint_build"
path = "src/lib.rs"

[dependencies]
